#!/usr/bin/env bash

function usage() {
	echo "Usage: $(basename $0) [user]" >&2
	exit 1
}

function report_single() {
	cat << EOT
SELECT '"' || mailbox || '",' || count(*) || ',' || count(found) FROM scans WHERE user='$1' GROUP BY mailbox;
EOT
}

function report_mismatches() {
	cat << EOT
SELECT DISTINCT(user) FROM scans WHERE found IS NOT 1;
EOT
}

if [ $# -gt 0 ]; then
	report_single "$1"
else
	report_mismatches
fi
